### ISSUE TITLE
Long Running Javascript does not continue running in the background on iOS

### ISSUE THREAD

**Issue by singerbj** [duyduong/interactive_webview#12]
I'm using an interactive webview to run a javascript library in the background of my flutter app. On android this long running library works just great, but on iOS it seems that the webview stops running, and stops being able to respond to evalJavascript. Are there different "rules" on iOS compared to Android when it comes to webviews in the background?

My code is here if you are interested: https://pastebin.com/evfJ21Qs

**Comment by duyduong** [comment]
Your link is not working, can u paste ur js code here?

**Comment by singerbj** [comment]
I have updated the link in my comment above. I expect a decent way of simulating this simply would be to run something in a setInterval() and see if it stays up. I'll try that quickly now and report back.

**Comment by singerbj** [comment]
There's also no console messages from the webview on ios. It makes debugging more difficult. Maybe you could patch the console functions to send a message back to dart?

**Comment by duyduong** [comment]
@singerbj Sorry for long time reply. So the long js should this `https://unpkg.com/peerjs@1.0.0/dist/peerjs.min.js` right? My suggestion is that u should this put into a HTML `script` tag, let it do the job.
Just create a html file, put your remote js into script tag in head, also put all your local script into that html. Using dart to read the file content and call `loadHTML` to load it

**Comment by singerbj** [comment]
@duyduong I'll give that a try, thanks. Really I should just use a webrtc library in dart but I don't feel like learning the architecture of webrtc :)
