### ISSUE TITLE
postMessage from Javascript is not getting captured in the Flutter

### ISSUE THREAD

**Issue by saarangtiwari** [duyduong/interactive_webview#13]
Messages from the Javascript to Webview( Flutter ) are not received.
I have tried sending events like:
```
window.postMessage('data');
postMessage('data');
```
I am expecting them to be received in the below callback:
```
jsWebview.didReceiveMessage.listen((message) {
      print(message.data);
    });

```

However, it is never received on the flutter end. Although, the communication from the flutter to javascript works.

**Comment by duyduong** [comment]
The window object does not contain postMessage method. Instead
`const nativeCommunicator = typeof webkit !== 'undefined' ? webkit.messageHandlers.native : window.native;`
Then, using `nativeCommunicator.postMessage`

**Comment by saarangtiwari** [comment]
@duyduong Thank you for your response. I am testing the same and let you know if it worked.

**Comment by saarangtiwari** [comment]
@duyduong It is working now. Thank you very much for the quick response.
