### ISSUE TITLE
WSS connections not supported in iOS

### ISSUE THREAD

**Issue by HeikoMueller** [duyduong/interactive_webview#16]
Hi. I have a html file that creates a new instance of the deepstream.io client library with the endpoint of a secure web socket connection as its argument. While this is running without any problem on Android, iOS does not connect. Can you confirm that wss is supposed to work for iOS in this plugin ? If this is expected behavior, is there a way to enable wss inside the interactive webview ?
Thank you !

**Comment by duyduong** [comment]
@HeikoMueller I believe it is iOS issue by blocking your wss, not my plugin. Can u try to do some research on that? Keywords would be `iOS WKWebview with WSS`
