### ISSUE TITLE
Modularize JS files

### ISSUE THREAD

**Issue by cTatu** [duyduong/interactive_webview#2]
Hi, I'm using a JS API and I'm wondering if I can use a single .js file from the 'asset' folder wit all my functions instead of the index.html file. Or at least be able to import a js file from the assets folder inside the index.html. 

Thank you and nice work! 😉

**Comment by duyduong** [comment]
There are 2 ways for you to import JS files:
- Put your JS files in a public host (Firebase storage, S3...). I usually put them to Firebase storage, change rule to allow public read these files then reference them to script src on index.html
- You can manually inject JS file content into script. For example:

index.html content:
```html
<!doctype html>
<html>
<head>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script>my_script_content</script>
</head>
<body>
</body>
</html>
```

```dart
final scriptContent = await rootBundle.loadString("assets/your_js_file.js", cache: false);
var html = await rootBundle.loadString("assets/index.html", cache: false);
html = html.replaceFirst(new RegExp(r'my_script_content'), scriptContent);

final webView = InteractiveWebView();
webView.loadHTML(html);
```

I prefer the first option, not only convenience but also for your later changes. You can update your JS files at any time without updating the app after released to App Store or Google Play.

**Comment by cTatu** [comment]
Thank you very much, that solved it! 👍 😄
