### ISSUE TITLE
Null print when postMessage from JS

### ISSUE THREAD

**Issue by cTatu** [duyduong/interactive_webview#3]
Hi, I was testing out your example and it worked totally fine but when I tried to modify the JS script inside the html file I encountered this problem when I try to send back to flutter the modified data. 
Do you know why happens this or any way to solve it? I tried also declaring global variables and storing the 'text' variable inside but nothing, still sends null.

Perhaps the `stateChanged WebViewState.didFinish` event has something to do?

Thank you!

### index.html
```html
<script>
    const nativeCommunicator = typeof webkit !== 'undefined' ? webkit.messageHandlers.native : window.native;
    function test(text) {
      var s = text + "123";
      console.log(s);
      nativeCommunicator.postMessage(JSON.stringify(s));
      //nativeCommunicator.postMessage(s);
    }
</script>
```
### Output
<pre>
I/flutter ( 9409): stateChanged WebViewState.didStart http://bilutv.net/
I/flutter ( 9409): stateChanged WebViewState.didFinish http://bilutv.net/
I/chromium( 9409): [INFO:CONSOLE(11)] "Hello from Native!!!123", source: http://bilutv.net/ (11)
I/flutter ( 9409): null             <b><--- THAT nativeCommunicator.postMessage</b>
</pre>

**Comment by duyduong** [comment]
Your variable ‘s‘ is not JSON. It is String, then just postMessage it, don't need to stringify it

postMessage method accepts String, if your post data is object or array, then stringify it before posting

I suggest to put your data in object, stringify it, then u can access it as a Map in Flutter

**Comment by cTatu** [comment]
I also tried with `postMessage(s)` and `postMessage(text)` but still get null. It's like that objects only exists in JS and when try to send them back to flutter just output null. It's very strange

**Comment by duyduong** [comment]
Can you show the Flutter code?

**Comment by cTatu** [comment]
Of course, I dind't modify anything in the dart main fail from your example. The only thing I modify the scrript inside de index.html.

If I put a breakpoint on `print(message.data)` line the message.name is 'native' and data is `null`.

I run it with flutter 1.0.0 and also with the last version but nothing changes.

### main.dart
```dart
class _MyAppState extends State<MyApp> {

  final _webView = InteractiveWebView();

  @override
  void initState() {
    super.initState();
    _webViewHandler();
  }

  _webViewHandler() async {
    _webView.didReceiveMessage.listen((message) {
      print(message.data);
    });

    _webView.stateChanged.listen((state) {
      print("stateChanged ${state.type} ${state.url}");
    });

    final html = await rootBundle.loadString("assets/index.html", cache: false);
    _webView.loadHTML(html, baseUrl: "http://bilutv.net/");
  }

  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      home: new Scaffold(
        appBar: new AppBar(
          title: const Text('Plugin example app'),
        ),
        body: new Center(
          child: new RaisedButton(onPressed: () {
            final text = "Hello from Native!!!";
            _webView.evalJavascript("test('$text')");
          }, child: Text("Send to WebView"))
        ),
      ),
    );
  }
}
```

### index.html
```html
<!doctype html>
<html>
<head>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
</head>
<body>
  <script>
    const nativeCommunicator = typeof webkit !== 'undefined' ? webkit.messageHandlers.native : window.native;
    function test(text) {
      var s = text + "123";
      console.log(s);
      nativeCommunicator.postMessage(s);
    }
  </script>
</body>
</html>
```

**Comment by duyduong** [comment]
Hey that's a good catch! I forgot an `else` when parsing post data from Javascript. I remembered that tested for both cases.

Anyway I just published new version. Can you check again?

**Comment by cTatu** [comment]
Now works like a charm, thank you very much! 😃
Beautiful work.
