### ISSUE TITLE
localStorage

### ISSUE THREAD

**Issue by Gorniv** [duyduong/interactive_webview#7]
I/chromium( 3269): [INFO:CONSOLE(1)] "Uncaught SecurityError: Failed to read the 'localStorage' property from 'Window': Storage is disabled inside 'data:' URLs."
How can i fix it?

**Comment by duyduong** [comment]
Can u show me the completed code? This maybe a bug from Android, please see this:
https://bugs.chromium.org/p/chromium/issues/detail?id=514076

**Comment by duyduong** [comment]
I will close this issue. Re-open if it is really an issue on my plugin
